### ISSUE TITLE
Module is not defined

### ISSUE THREAD

**Issue by AmdEagle** [ttyridal/openh264-js#2]
I cloned your git and ran the make file. When serving the Webpage on the browser i and getting this error Module is not Defined.

Do you have an updated version of the openh264.-js ?
I am trying project where i need to take in h264( Main profile  ) byte array of stream from websocket and display / play it on a canvas. And i was trying our your project.

Do you have any latest version that you have which will be great help to me.

**Comment by ttyridal** [comment]
Sorry, I haven't done the exercise for any newer version, 

I've uploaded my successful build as a release, hope that can help you

**Comment by AmdEagle** [comment]
Thank you for the release build.  have tried it and i was able to decode the incoming h264 stream.. But there seems to a delay that keep one increasing.. Any idea what i am doing wrong ?

As when it starts the video is of current time then its starts to lag and also the video play is very slow like it is playing in slow motion. Any setting that i have to set before decoding the file ?
